symfony/src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $approved;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $remarks;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $booked_by;

    /**
     * @ORM\Column(type="decimal", precision=30, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\GreaterThanOrEqual(
     *      value = "today",
     *      message = "The date should be greater than today!",
     *      groups={"new_order"}
     * )
     */
    private $from_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Assert\GreaterThanOrEqual(
     *      value = "today",
     *      message = "The date should be greater than today!",
     *      groups={"new_order"}
     * )
     * @Assert\Expression(
     *     "this.getUntilDate() >= this.getFromDate()",
     *     message="The from date should start before the end date!",
     *     groups={"new_order"}
     * )
     */
    private $until_date;

    /**
     * @ORM\ManyToOne(targetEntity="Office")
     */
    private $office;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getApproved(): ?bool
    {
        return $this->approved;
    }

    public function setApproved(?bool $approved): self
    {
        $this->approved = $approved;

        return $this;
    }

    public function getRemarks(): ?string
    {
        return $this->remarks;
    }

    public function setRemarks(string $remarks): self
    {
        $this->remarks = $remarks;

        return $this;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function getBookedBy(): ?int
    {
        return $this->booked_by;
    }

    public function setBookedBy(?int $booked_by): self
    {
        $this->booked_by = $booked_by;

        return $this;
    }

    public function getFromDate(): ?\DateTimeInterface
    {
        return $this->from_date;
    }

    public function setFromDate(?\DateTimeInterface $from_date): self
    {
        $this->from_date = $from_date;

        return $this;
    }

    public function getUntilDate(): ?\DateTimeInterface
    {
        return $this->until_date;
    }

    public function setUntilDate(?\DateTimeInterface $until_date): self
    {
        $this->until_date = $until_date;

        return $this;
    }

    public function getOffice(): ?Office
    {
        return $this->office;
    }

    public function setOffice(Office $office): self
    {
        $this->office = $office;

        return $this;
    }
}

symfony/src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('from_date')
            ->add('remarks')
            ->add('until_date');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

symfony/src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Office;
use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/order")
 */
class OrderController extends AbstractController
{
    /**
     * @Route("", name="order_index", methods={"GET"})
     */
    public function index(OrderRepository $orderRepository): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }

        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAllByBookedUser($this->getUser()->getId()),
        ]);
    }

    /**
     * @Route("/new/{id}", name="order_new", methods={"GET","POST"})
     */
    public function new(Request $request, $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        $order = new Order();
        $office = $entityManager->getRepository(Office::class)->find($id);
        $order->setOffice($office);
        $user = $this->getUser();
        $order->setBookedBy($user->getId());
        $form = $this->createForm(OrderType::class, $order, ['validation_groups' => 'new_order']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $order->setPrice($order->getFromDate()->diff($order->getUntilDate())->days * $office->getPrice());
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('order_index');
        }

        return $this->render('order/new.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="order_show", methods={"GET"})
     */
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="order_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Order $order): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('order_index');
        }

        return $this->render('order/edit.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="order_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('delete' . $order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('order_index');
    }

    /**
     * @Route("/approve/{id}", name="order_approve", methods={"POST"})
     */
    public function approve(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('update' . $order->getId(), $request->request->get('_token'))) {
            $this->updateApprovedOrder($order, TRUE);
        }

        return $this->redirectToRoute('my-offices-for-renting');

    }

    /**
     * @Route("/reject/{id}", name="order_reject", methods={"POST"})
     */
    public function reject(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('update' . $order->getId(), $request->request->get('_token'))) {
            $this->updateApprovedOrder($order, FALSE);
        }

        return $this->redirectToRoute('my-offices-for-renting');
    }

    /**
     * Update approved status of an order.
     *
     * @param Order $order
     * @param $approved
     */
    public function updateApprovedOrder(Order $order, $approved)
    {
        $order->setApproved($approved);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($order);
        $entityManager->flush();
    }

}

symfony/templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Orders{% endblock %}

{% block body %}
    <div class="col-10 offset-1">
        <h1>My orders</h1>

        <table class="table table-striped table-m">
            <thead>
            <tr>
                <th>Id</th>
                <th>Office</th>
                <th>Price</th>
                <th>From</th>
                <th>Until</th>
                <th>Approved</th>
                <th>Remarks</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.office ? order.office.id : '' }}</td>
                    <td>${{ order.price }}</td>
                    <td>{{ order.fromDate ? order.fromDate|date('Y-m-d') : '' }}</td>
                    <td>{{ order.untilDate ? order.untilDate|date('Y-m-d') : '' }}</td>
                    <td>
                        {% if order.approved  == '0' %}
                            <span class="badge badge-pill badge-danger">Rejected</span>
                        {% elseif order.approved  == '1' %}
                            <span class="badge badge-pill badge-success">Approved</span>
                        {% else %}
                            <span class="badge badge-pill badge-primary">Pending</span>
                        {% endif %}
                    </td>
                    <td>{{ order.remarks }}</td>
                    <td>
                        <a href="{{ path('order_show', {'id': order.id}) }}">show</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

symfony/templates/order/new.html.twig
{# templates/order/new.html.twig #} {% extends 'base.html.twig' %}


{% block body %}
    <div class="container">
        <div class="offices-header">
            <h2 class="offices-title">Create new Order</h2>
        </div>
        <div class="col-md-10 ml-md-auto">
            <div class="card bg-light mb-3 mt-5" style="width: 800px">
                <div class="card-body">
                    <div class="card-header mb-3">New order</div>
                    {{ form_start(form) }}
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {{ form_row(form.from_date, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {{ form_row(form.until_date, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form_group">
                        <div class="col-md-12 mb-3">
                            {{ form_row(form.remarks, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4" style="margin-top:5px;">

                            <button type="submit" class="btn btn-primary">
                                <i class="fa fa-btn fa-user"></i> Save
                            </button>
                        </div>
                    </div>

                    {{ form_end(form, {'render_rest': true}) }}

                    <a href="/">back to homepage</a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

symfony/templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>ID</th>
            <td>{{ order.id }}</td>
        </tr>
        <tr>
            <th>Approved</th>
            <td>{{ order.approved ? 'Yes' : 'No' }}</td>
        </tr>
        <tr>
            <th>Remarks</th>
            <td>{{ order.remarks }}</td>
        </tr>
        <tr>
            <th>From</th>
            <td>{{ order.fromDate ? order.fromDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Until</th>
            <td>{{ order.untilDate ? order.untilDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>${{ order.price }}</td>
        </tr>
        <tr>
            <th>Office</th>
            <td>{{ order.office ? order.office.id : '' }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('order_index') }}">back to my orders</a>

{% endblock %}